### ISSUE TITLE
Error on astro-core.js

### ISSUE THREAD

**Issue by Marimatcha** [Narendra-Kamath/indian-astrology#1]
Had an Error on `` if (f.birthYear < 1800 || f.birthMonth > 2100) {
                    throw new Error('Year should be between 1800 and 2100');
}``
I think it should be:
`` if (f.birthYear < 1800 || f.birthYear > 2100) {
                    throw new Error('Year should be between 1800 and 2100');
}``

**Comment by Narendra-Kamath** [comment]
Thank you @Marimatcha for pointing out the issue. The issue is fixed and I am closing this issue.
